name: Typescript Examples

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "node/**"
      - "browser/**"
      - ".github/workflows/*typescript*"
  push:
    branches:
      - main
    paths:
      - "node/**"
      - "browser/**"
      - ".github/workflows/*typescript*"

jobs:
  test_typescript:
    name: Build Node & Browser Samples
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest]
        node-version: [ 16, 18 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: Setup Node v${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build Node Demo
        run: |
          npm install
          npm run demo
        shell: pwsh
        working-directory: ./node/basic
      - name: Build Basic Webpack Demo
        run: |
          npm install
          npm run build
        shell: pwsh
        working-directory: ./browser/basic-webpack
      # TODO - Enable this @MichaelEdwardBlack
      # - name: Build Browser Demo
      #   run: |
      #     npm install
      #     npm run test
      #   shell: pwsh
      #   working-directory: ./browser/react-wallet